---
title: "Testing OPM -- OLS Trump -- 100 ANES Observations -- 1 Run"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{dcolumn}
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(blockTools)
library(stargazer)
library(here)

test.ols.trump.orig <- test.ols.trump.new <- readRDS(here("data", "anes_education.rds")) 

test.ols.trump.new$education = test.ols.trump.new$education.new # so that I can run the rest of the code easily in a loop
list.test.ols.trump <- list(test.ols.trump.orig, test.ols.trump.new)
listing <- list()
lm.out <- list()

for (i in 1:length(list.test.ols.trump)){
  list.test.ols.trump[[i]]$education <- as.numeric(list.test.ols.trump[[i]]$education)
  list.test.ols.trump[[i]]$id <- 1:nrow(list.test.ols.trump[[i]])
  list.test.ols.trump[[i]] <- list.test.ols.trump[[i]][c(1:100), ]
  listing[[i]] <- assignment(block(list.test.ols.trump[[i]], n.tr = 2, id.vars = c("id"), block.vars = c("education")), seed = 123)
  list.test.ols.trump[[i]]$treat1 <- ifelse(list.test.ols.trump[[i]]$id %in% which(list.test.ols.trump[[i]]$id %in% unname(listing[[i]]$assg[[1]][,1])), "treat1", NA)
  list.test.ols.trump[[i]]$treat2 <- ifelse(list.test.ols.trump[[i]]$id %in% which(list.test.ols.trump[[i]]$id %in% unname(listing[[i]]$assg[[1]][,2])), "treat2", NA)
  list.test.ols.trump[[i]]$group <- factor(c(na.omit(c(t(list.test.ols.trump[[i]][,c("treat1", "treat2")])))))
  list.test.ols.trump[[i]]$rep <- ifelse(list.test.ols.trump[[i]]$pid == "Republican", 1, 0)
  list.test.ols.trump[[i]]$dem <- ifelse(list.test.ols.trump[[i]]$pid == "Democrat", 1, 0)
  list.test.ols.trump[[i]]$male <- ifelse(list.test.ols.trump[[i]]$gender == "Male", 1, 0)
  list.test.ols.trump[[i]]$white <- ifelse(list.test.ols.trump[[i]]$race == "White", 1, 0)
  list.test.ols.trump[[i]]$black <- ifelse(list.test.ols.trump[[i]]$race == "African-American", 1, 0)
  list.test.ols.trump[[i]]$hisp <- ifelse(list.test.ols.trump[[i]]$race == "Hispanic", 1, 0)
  list.test.ols.trump[[i]]$income.num <- as.numeric(list.test.ols.trump[[i]]$income)
  lm.out[[i]] <- lm(feel.trump ~ group + dem + rep + male + white + black + hisp + income.num + age, data = list.test.ols.trump[[i]])
}

```

```{r results='asis', echo=FALSE}
stargazer(lm.out[[1]], lm.out[[2]], 
          header = FALSE,
          title = "OLS After Blocking on Education into 2 Treatment Groups",
          dep.var.labels   = "Feeling Thermometer Trump",
          column.labels = c("Original Educ Categories", "OPM Educ Categories"),
          model.numbers = FALSE,
          no.space = TRUE,
          star.cutoffs = NA,
          omit.table.layout = "n",
          single.row = TRUE,
          align = TRUE)
```


