---
title: |
  | Analyzing Online Survey Experiments
  | &mdash;
  | Sequential Blocking, Mode Effects, and the Power of Moral Arguments
author: |
  | **PhD Dissertation Prospectus Defense**
  | Simon Heuberger
  | Department of Government
  |
  | 13 April 2018
titlegraphic: /Users/simonheuberger/Dropbox/work/logo.png
fontsize: 10pt
output:
  beamer_presentation:
    template: /Users/simonheuberger/Dropbox/work/markdown_templates/beamer_template_svm_conferences.tex
  slide_level: 1
bibliography: /Users/simonheuberger/Dropbox/work/bib_files/all_together.bib
---

# Outline

* Methods dissertation about online survey experiments
* Three papers
    + Two quantitative methods contributions
    + One application in American Politics
* Paper I: Improving Balance in Online Survey Experiments
* Paper II: Uncovering Mode Effects in Online Survey Experiments
* Paper III: Moral Arguments as a Source of Frame Strength


# 

\centering \LARGE \textcolor{pigmentblue}{Paper I: Improving Balance in Online Survey Experiments}



# I: Overview

* Problem:
    + Majority of online surveys use Qualtrics to design questionnaire
    + Qualtrics only offers complete randomization
    + Fine for large samples, but not for small samples
    + Large samples are expensive
* Solution
    + Sophisticated method of randomization called sequential blocking
    + Software tool that makes this method applicable to other researchers



# I: Complete Randomization and Blocking

\begin{table}[H]
\caption{Randomization in Experiments}
\centering
\begin{tabular}{*{2}{l}}
\bottomrule 
\midrule
Unit Characteristics Are Known & Unit Characteristics Are Not Known\\
\midrule
Complete Randomization & Complete Randomization\\
`Nonsequential' Blocking & -------- \\
-------- & Sequential Blocking\\
\bottomrule
\end{tabular}
\label{seq_rand_overview}
\end{table} 


# I: Sequential Blocking

* Covariate-adaptive randomization (CAR)
    + Varies probabilities of assignment based on knowledge about previous units and the current unit
* Basic CAR
    + Biased coin
    + Minimization
* Advanced CAR
    + Continuous variables
* My contribution: CAR for ordinal outcome variables 



# I: Software Tool

* R package
    + Creates questionnaire that can be directly fielded online
    + Applies sequential blocking method
    + Freely available to other researchers
* MTurk
    + Package designed to be linked to MTurk to recruit participants
* Qualtrics
    + Free, more sophisticated alternative to Qualtrics



# I: Data Applications

* Simulations
    + Sequentially block using the mean Mahalanobis distance
    + Complete randomization with same settings
* External
    + Studies that use complete randomization and OLS covariate controls
    + Sequentially block respondents in the data
    + Order of observations is sequential entry order
    + Example: Tomz and Weeks (2013)
* Original
    + Online survey experiment in paper III
        - Once with sequential blocking
        - Once with complete randomization







# 

\centering \LARGE \textcolor{pigmentblue}{Paper II: Uncovering Mode Effects in Online Survey Experiments}


# II: Overview

* Problem
    + Online surveys are popular, fast, cheap
    + BUT: Changing modes influences how respondents answer questions
    + Lots of research, we know lots of differences
    + BUT: Is there a measurement error in the form of a critical distributional difference in aggregate survey responses?
* Solution
    + Entropy measure
    + Describes measurement variability in categorical questions
    + Measures of variance that assume continuous data (i.e. SD) not suitable
    + How respondents react to identical questions in different survey modes
    + Only applied to comparison between face-to-face and online so far
    
    

# II: Pathologies of Online Surveys

* Sampling error
* Nonresponse
* Social desirability
* Satisficing
* Total survey error


# Entropy Measure

* Evidence of effect of mode differences on survey responses is mixed
* Traditional statistical measurements (variance, median average deviation) robust to ordinal data with equally spaced distances
* Most surveys and survey experiments have non-equally spaced ordinal data
    + Likert scale of support
    + Ideology measure
* Entropy measure $H$, for a given discrete variable $f(X)=[p_1,p_2,...,p_k]$:
$$H = - \sum p_i ln(p_i), \sum p_i = 1$$

    $p_i$: observed counts for each possible answer category of survey variable



# II: Data Applications

* External
    + Data sets that field identical questions on the phone and online
    + Examples: ANES 2016, Pew surveys
* Original
    + Online survey experiment in paper III
    + Complementary RDD survey through TESS




# 

\centering \LARGE \textcolor{pigmentblue}{Paper III: Moral Arguments as a Source of Frame Strength}

# III: Overview

* Problem
    + Framing shown to have effects
    + Some frames work, others don't
    + We don't know what makes a frame strong
* Solution
    + Moral arguments could form part of frame strength
    + Moral arguments as the key IV


# III: Framing and Moral Arguments

* Framing
    + Presenting an issue in certain terms to influence how people perceive it
    + Changed level of issue support as a result of frame exposure
    + Mixed findings on sources of frame strength
* Moral arguments
    + Based on ethics, fairness, equality
    + Important force in shaping public opinion
    + Moral Foundations Theory


# III: Data

* Preliminary analyses
    + Meta-Analysis of experimental framing studies
    + Online poll to test strong frames from previous studies on moral content
        - Fielded on MTurk
    + Focus group on how people define moral arguments
        - Fielded with DC company
* Main analysis: Online survey experiment to test power of moral arguments
    + Design complementary nonmoral frames to strong frames from studies
    + Pre-test designed frames on MTurk
    + Field questionnaire on MTurk with sequential blocking (Paper I)
    + Analyze entropy results in identical survey fielded on TESS (Paper II)




# 

\centering \LARGE \textcolor{pigmentblue}{Thank you!}
