---
title: "Regressions and Balance Tests"
author: "Simon Heuberger"
date: "12/13/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(RItools)
library(stargazer)
library(here)
library(tidyverse)
library(magrittr)
library(xtable)
```

```{r include=FALSE}

########################################################## Analysis of first batch only ##########################################################

### Prepare data for batch 1 (sort out failed checks, remove the unimportant columns, take out NAs) ###

df.all.1 <- read.csv(here("data", "pre-test", "batch.1.csv"), na.strings = "NA")
df.all.1[27, "hc.check"] <- 3 # this guy commented that he accidentally clicked the wrong option, so I'm adjusting this and not rejecting him

df.all.1 <- df.all.1[!duplicated(df.all.1$unique.id), ] # remove duplicate unique.ids (some MTurk error somewhere)
summary(is.na(df.all.1))

df.first.batch.no.att.na.fail <- df.all.1[!is.na(df.all.1$att),] %>% # where there are no att == NA
  filter(., att != 2) # everyone who has failed at least one check
df.first.batch.att.na <- df.all.1[is.na(df.all.1$att),] # where att == NA

df.first.batch.fail <- rbind(df.first.batch.no.att.na.fail, df.first.batch.att.na)
nrow(df.first.batch.fail) # 31 people failed the pre-treatment attention check

df.first <- filter(df.all.1, !unique.id %in% df.first.batch.fail$unique.id)
nrow(df.first) # 207 people passed the pre-treatment attention check

throw.away.first <- select(df.first, .online.length, .study.choice, online.why) # save throw away columns separately
comments.first <- na.omit(df.first$com) # save comments separately

discard.cols <- c(".online.length", ".study.choice", "online.why", "com", "att", "ev.check", "hc.check", "unique.id")
df.first <- select(df.first, -one_of(discard.cols)) # remove unneeded columns

df.first[rowSums(is.na(df.first)) > 0,] %>% nrow # 11 people with NAs
summary(is.na(df.first))

df.first.omit <- na.omit(df.first)
nrow(df.first) # 207 people overall for me to work with

df.first.omit <- df.first.omit %>% rename(educ = ed.both)
df.first.omit$inc.num <- df.first.omit$inc
cols.fac <- c("educ", "race", "gender", "empl", "inc", "pid", "ideol")
for (i in 1:length(cols.fac)){
    df.first.omit[,cols.fac[i]] <- factor(df.first.omit[,cols.fac[i]])
  }
levels(df.first.omit$educ) <- readRDS(here("data", "anes", "anes_education.rds")) %>% 
  .$education.new %>% 
  levels

questions.path <- "/Users/simonheuberger/dissertation/shiny/questions"
questions.files <- paste0(c("demographics1", "demographics2", "pid", "ideol"), ".csv")

varNames <- function(df, varName){
  filter(df, id == varName) %>% 
    select(., choiceNames) %>% 
    .[,1] %>% 
    strsplit(., ",") %>%
    .[[1]]
} # to extract the var names from the .csv question files

varChoices <- function(df, varName){
  filter(df, id == varName) %>% 
    select(., choices) %>% 
    .[,1] %>% 
    strsplit(., ",") %>%
    .[[1]]
} # to extract the numeric var choices from the files

refactor <- function(df, var, varn){
  if(length(levels(df[, var])) == length(varn)){
      levels(df[, var]) <- varn
      df[, var]
      }else{
        stop("Not all levels are present in data. Rename factors by hand!")
      }
} # refactor the numeric levels with the character versions

var <- "race"
q1 <- read.csv(paste0(questions.path, "/", questions.files[1])) # dems1 for race, gender
varn <- varNames(q1, var)
refactor(df.first.omit, var, varn)  
varLev <- levels(df.first.omit[, var])
varLev
varn
df.first.omit[, var] <- fct_recode(df.first.omit[, var],
                                   "White" = "1",
                                   "Black" = "2",
                                   "Hispanic" = "3",
                                   "Asian" = "4",
                                   "Arab" = "5",
                                   "American Indian or Alaska Native" = "6",
                                   "Other" = "8")

var <- "gender"
varn <- varNames(q1, var)
df.first.omit[, var] <- refactor(df.first.omit, var, varn)

q2 <- read.csv(paste0(questions.path, "/", questions.files[2])) # dems2 for empl, inc
var <- "empl"
varn <- varNames(q2, var)
df.first.omit[, var] <- refactor(df.first.omit, var, varn)

var <- "inc"
varn <- varNames(q2, var)
df.first.omit[, var] <- refactor(df.first.omit, var, varn)

q3 <- read.csv(paste0(questions.path, "/", questions.files[3])) # pid for pid
var <- "pid"
varn <- varNames(q3, var)
df.first.omit[, var] <- refactor(df.first.omit, var, varn)

q4 <- read.csv(paste0(questions.path, "/", questions.files[4])) # ideol for ideol
var <- "ideol"
varn <- varNames(q4, var)
df.first.omit[, var] <- refactor(df.first.omit, var, varn)

df.first.omit$pid.follow <- df.first.omit$pid.follow %>% as.character # pid.follow needs to be separate, it's more complicated
qdem <- read.csv(paste0(questions.path, "/pid.foll.dem.csv"))
qind <- read.csv(paste0(questions.path, "/pid.foll.ind.else.csv"))
var <- "pid.follow"
varndem <- varNames(qdem, var)
varnind <- varNames(qind, var)

for(i in 1:nrow(df.first.omit)){
  if(df.first.omit[i, "pid"] == "Democrat" | df.first.omit[i, "pid"] == "Republican"){
    df.first.omit[i, "pid.follow"] <- ifelse(df.first.omit[i, "pid.follow"] == 1, varndem[1], varndem[2])
  } else {
    df.first.omit[i, "pid.follow"] <- ifelse(df.first.omit[i, "pid.follow"] == 1, varnind[1], 
                                  ifelse(df.first.omit[i, "pid.follow"] == 2, varnind[2], varnind[3]))
  }
}

df.first.omit$pid.follow <- df.first.omit$pid.follow %>% as.factor
df.first.omit$ideol.follow <- df.first.omit$ideol.follow %>% as.character # ideol.follow needs to be separate, also more complicated
qlib <- read.csv(paste0(questions.path, "/ideol.foll.lib.csv"))
qcons <- read.csv(paste0(questions.path, "/ideol.foll.cons.csv"))
qnei <- read.csv(paste0(questions.path, "/ideol.foll.nei.csv"))
var <- "ideol.follow"
varnlib <- varNames(qlib, var)
varncons <- varNames(qcons, var)
varnnei <- varNames(qnei, var)

for(i in 1:nrow(df.first.omit)){
  if(df.first.omit[i, "ideol"] == "Liberal"){
    df.first.omit[i, "ideol.follow"] <- ifelse(df.first.omit[i, "ideol.follow"] == 1, varnlib[1], varnlib[2])
  } else if(df.first.omit[i, "ideol"] == "Conservative"){
    df.first.omit[i, "ideol.follow"] <- ifelse(df.first.omit[i, "ideol.follow"] == 1, varncons[1], varncons[2])
  } else {
    df.first.omit[i, "ideol.follow"] <- ifelse(df.first.omit[i, "ideol.follow"] == 1, varnnei[1], 
                                    ifelse(df.first.omit[i, "ideol.follow"] == 2, varnnei[2], varnnei[3]))
  }
}

df.first.omit$ideol.follow <- df.first.omit$ideol.follow %>% as.factor

# birthyear input is 1:83. The corresponding birthyears are 2002:1920
# I want to replace the input with the corresponding birthyears
# To get from birthyear input 1 to actual birthyear 2002, you add 2001. To get from 2 to 2001, you add 1999. To get from 3 to 2000, you add 1997. Etc.
# You start with 2001. For every number you go up in birthyear input, you add a number going downward from 2001 by a sequence of 2 to the birthyear input
# Then you have a column of the actual birthyears. To get the age, subtract each actual birthyear from 2020

var <- "birthyear"
years <- varNames(q1, var) %>% as.numeric
year.inp <- varChoices(q1, var) %>% as.numeric
year.seq.start <- max(years) - min(year.inp) # the first number to add (2001) to the lowest birthyear input (1)
year.dist <- max(year.inp)-min(year.inp) # the distance between the highest and lowest birthyear input (82)
year.seq.end <- year.seq.start - (year.dist * 2) # the last number to add (1837) to the highest birthyear input (83)
year.seq <- seq(from = year.seq.end, to = year.seq.start, by = 2) %>% rev # all the numbers to add to each increasing number in birthyear input

for(i in 1:nrow(df.first.omit)){
  for(x in 1:length(year.inp)){
    if(df.first.omit[i, "birthyear"] == year.inp[x]){
      df.first.omit[i, "age"] <- 2020 - (year.inp[x] + year.seq[x])
    }
  }
}

df.first.omit <- select(df.first.omit, -one_of("birthyear")) # I tried simply overwriting column birthyear in the loop, but that kept giving really weird numbers. No idea why
df.first.omit$dem <- ifelse(df.first.omit$pid == "Democrat", 1, 0)
df.first.omit$male <- ifelse(df.first.omit$gender == "Male", 1, 0)
df.first.omit$mor.all <- (df.first.omit$mor.suffer + df.first.omit$mor.care + df.first.omit$mor.cruel +
                 df.first.omit$mor.comp + df.first.omit$mor.anim + df.first.omit$mor.kill) / 6
df.first.omit$si.all <- (df.first.omit$si.white + df.first.omit$si.care + df.first.omit$si.kids + 
                df.first.omit$si.kill + df.first.omit$si.good + df.first.omit$si.help) / 6

write.csv(df.first.omit, file = here("data", "pre-test", "batch.1.only.att.passed.csv"), row.names = FALSE)

hc.lm.out <- lm(hc.likert ~ hc.group + mor.all + si.all + dem + empl + inc, data = df.first.omit)
ev.lm.out <- lm(ev.likert ~ ev.group + mor.all + si.all + dem + empl + inc, data = df.first.omit)

df.first.omit$hc.group.num <- df.first.omit$hc.group %>% as.factor %>% as.numeric
balance <- xBalance(hc.group.num ~ race + gender + empl + inc + pid + educ + age, 
                    data = df.first.omit, 
                    report = c("std.diffs", "z.scores", "adj.means", "adj.mean.diffs", 
                               "adj.mean.diffs.null.sd", "chisquare.test", "p.values"))
listed <- lapply(seq(dim(balance$results)[3]), function(x) balance$results[ , , x])
balance.df <- plyr::ldply(listed, data.frame, .id = NULL)
balance.df$vars <- c(paste0("race", levels(df.first.omit$race)), paste0("gender", levels(df.first.omit$gender)), 
                     paste0("empl", levels(df.first.omit$empl)), paste0("inc", levels(df.first.omit$inc)), 
                     paste0("pid", levels(df.first.omit$pid)), paste0("educ", levels(df.first.omit$educ)), 
                     "age")
balance.df <- balance.df[, c(8,1:7)]
```


```{r Count, include = TRUE}
group_by(df.first.omit, hc.group) %>% summarize(count = n())
group_by(df.first.omit, ev.group) %>% summarize(count = n())

```

\clearpage

```{r Results, results='asis', echo=FALSE}

stargazer(hc.lm.out, header = FALSE,
          title = "Healthcare Regression Results",
          label = "hc.reg",
          single.row = TRUE)

stargazer(ev.lm.out, header = FALSE,
          title = "Environment Regression Results",
          label = "ev.reg",
          single.row = TRUE)

```

\clearpage

\begin{verbatim}
hc.group.num ~ race + gender + empl + inc + pid + educ + age, data = df.first.omit, 
    report = c("std.diffs", "z.scores", "adj.means", "adj.mean.diffs", 
    "adj.mean.diffs.null.sd", "chisquare.test", "p.values")
\end{verbatim}                               
                              

```{r Balance, results='asis', echo=FALSE, message=FALSE}
xtable(balance.df, caption = "Balance Across Covariates") %>% print(., comment=FALSE, include.rownames=FALSE)
xtable(balance$overall, caption = "Chi-squared test") %>% print(., comment = FALSE, include.rownames=FALSE)
```


```{r Plot-Balance, echo=FALSE, fig.width=10, fig.height=6, fig.cap="Balance Plot"}
plot(balance)
```



