---
title: "Regressions and Balance Tests"
author: "Simon Heuberger"
date: "12/13/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(RItools)
library(stargazer)
library(here)
library(tidyverse)
library(magrittr)
library(xtable)
```



```{r include=FALSE}
df.all <- read.csv(here("data", "experiment", "op.clean.csv"), as.is = TRUE)

cols.fac <- c("educ", "race", "gender", "empl", "inc", "pid", "ideol")
for (i in 1:length(cols.fac)){
    df.all[,cols.fac[i]] <- factor(df.all[,cols.fac[i]])
}

hc.lm.out <- lm(hc.likert ~ hc.group + mor.all + si.all + dem + empl + inc, data = df.all)

df.all$hc.group.num <- df.all$hc.group %>% as.factor %>% as.numeric
hc.balance <- xBalance(hc.group.num ~ race + gender + empl + inc + pid + educ + age, 
                    data = df.all, 
                    report = c("std.diffs", "z.scores", "adj.means", "adj.mean.diffs", 
                               "adj.mean.diffs.null.sd", "chisquare.test", "p.values"))
hc.balance.list <- lapply(seq(dim(hc.balance$results)[3]), function(x) hc.balance$results[ , , x])
hc.balance.df <- plyr::ldply(hc.balance.list, data.frame, .id = NULL)
hc.balance.df$vars <- c(c("White", "Black", "Hispanic", "Asian", "Arab", "Indian", "Hawaiian", "Other"), 
                     paste0("gender", levels(df.all$gender)), 
                     paste0("empl", levels(df.all$empl)), paste0("inc", levels(df.all$inc)), 
                     paste0("pid", levels(df.all$pid)), paste0("educ", levels(df.all$educ)), 
                     "age")
hc.balance.df <- hc.balance.df[, c(8,1:7)]

```

```{r include=FALSE}

ev.lm.out <- lm(ev.likert ~ ev.group + mor.all + si.all + dem + empl + inc, data = df.all)

df.all$ev.group.num <- df.all$ev.group %>% as.factor %>% as.numeric
ev.balance <- xBalance(ev.group.num ~ race + gender + empl + inc + pid + educ + age, 
                    data = df.all, 
                    report = c("std.diffs", "z.scores", "adj.means", "adj.mean.diffs", 
                               "adj.mean.diffs.null.sd", "chisquare.test", "p.values"))
ev.balance.list <- lapply(seq(dim(ev.balance$results)[3]), function(x) ev.balance$results[ , , x])
ev.balance.df <- plyr::ldply(ev.balance.list, data.frame, .id = NULL)
ev.balance.df$vars <- c(c("White", "Black", "Hispanic", "Asian", "Arab", "Indian", "Hawaiian", "Other"), 
                     paste0("gender", levels(df.all$gender)), 
                     paste0("empl", levels(df.all$empl)), paste0("inc", levels(df.all$inc)), 
                     paste0("pid", levels(df.all$pid)), paste0("educ", levels(df.all$educ)), 
                     "age")
ev.balance.df <- ev.balance.df[, c(8,1:7)]

```


```{r Count, include = TRUE}
group_by(df.all, hc.group) %>% summarize(count = n())
group_by(df.all, ev.group) %>% summarize(count = n())

```

\clearpage

```{r Results, results='asis', echo=FALSE}

stargazer(hc.lm.out, header = FALSE,
          title = "Healthcare Regression Results",
          label = "hc.reg",
          single.row = TRUE,
          star.char = c("", "", ""),
          omit.table.layout = "n")

stargazer(ev.lm.out, header = FALSE,
          title = "Environment Regression Results",
          label = "ev.reg",
          single.row = TRUE,
          star.char = c("", "", ""),
          omit.table.layout = "n")

```

\clearpage

\begin{verbatim}
group.num ~ race + gender + empl + inc + pid + educ + age, data = df.first.omit, 
    report = c("std.diffs", "z.scores", "adj.means", "adj.mean.diffs", 
    "adj.mean.diffs.null.sd", "chisquare.test", "p.values")
\end{verbatim}                               
                              

```{r Balance, results='asis', echo=FALSE, message=FALSE}
xtable(hc.balance.df, caption = "Balance Across Covariates") %>% print(., comment=FALSE, include.rownames=FALSE)
xtable(hc.balance$overall, caption = "Chi-squared test") %>% print(., comment = FALSE, include.rownames=FALSE)

xtable(ev.balance.df, caption = "Balance Across Covariates") %>% print(., comment=FALSE, include.rownames=FALSE)
xtable(ev.balance$overall, caption = "Chi-squared test") %>% print(., comment = FALSE, include.rownames=FALSE)
```

\clearpage


```{r Plot-Balance, echo=FALSE, fig.width=10, fig.height=6, fig.cap="Balance Plot"}
plot(hc.balance)
plot(ev.balance)
```



