---
title: "Regressions etc."
author: "Simon Heuberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(RItools)
library(stargazer)
library(here)
library(tidyverse)
library(magrittr)
library(xtable)
```



```{r include=FALSE}
df <- read.csv(here("data", "experiment", "op.clean.csv"), as.is = TRUE)

cols.fac <- c("educ", "race", "gender", "empl", "inc", "pid", "ideol")
for (i in 1:length(cols.fac)){
    df[,cols.fac[i]] <- factor(df[,cols.fac[i]])
}

hc.lm.out <- lm(hc.likert ~ hc.group + mor.all + si.all + dem + empl + inc, data = df)
ev.lm.out <- lm(ev.likert ~ ev.group + mor.all + si.all + dem + empl + inc, data = df)

```


```{r Count, include = TRUE}
group_by(df, hc.group) %>% summarize(count = n())
group_by(df, ev.group) %>% summarize(count = n())

```

\clearpage

```{r Results, results='asis', echo=FALSE}

stargazer(hc.lm.out, header = FALSE,
          title = "Healthcare Regression Results",
          label = "hc.reg",
          single.row = TRUE,
          star.char = c("", "", ""),
          omit.table.layout = "n")

stargazer(ev.lm.out, header = FALSE,
          title = "Environment Regression Results",
          label = "ev.reg",
          single.row = TRUE,
          star.char = c("", "", ""),
          omit.table.layout = "n")

```



