# MORALS, SELF-INTEREST, AND FRAME STRENGTH {#framing}

## Introduction {#framing-intro}

<!--
Barack Obama presented the first outline of the Affordable Care Act in the summer of 2009. The content of the reform was put online for everyone to see, but since the administration was still working on details, it refrained from actively communicating it. Published press releases simply stated that the ACA would expand coverage and lower healthcare costs for everyone. This hesitancy turned out to be a big mistake. At the end of July, support for the ACA hovered around 43 percent. Then Sarah Palin, John McCain's choice for running mate in 2008, posted the following statement on Facebook on August 7\textsuperscript{th}: "The America I know and love is not one in which my parents or my baby with Down Syndrome will have to stand in front of Obama's 'death panel' so his bureaucrats can decide, based on a subjective judgment of their 'level of productivity in society'" [@palin_statement_2009]. Palin implied that federal government workers would be able to refuse treatment to any patients and thus 'decide their fate'. Over the next two weeks, support for the ACA dropped to 35 percent while opposition rose to 52 percent. Republican lawmakers jumped at the opportunity and repeated the claim of 'death panels' whenever possible. The reform never recovered from this drop. In December 2009, four months after the statement, support and opposition were virtually identical to August. While the public was still uncertain about the exact contents of the law, Palin had asserted that it would include a Big Brother type panel that decided whether people would live or die. This drowned out any efforts by the Obama administration to show the law as a cost-reducing reform. Palin's frame of the ACA, in other words, drastically influenced public opinion of the reform.
-->

In today's world, we rarely consume information directly, for instance by attending a demonstration or listening to a talk. Instead, most of the information we consume is mediated through television, radio, blogs, social media, messenger apps, and so forth. Mediated information by definition only represent a selective fragment of reality. The messenger -- news anchors, pundits, influencers, politicians etc. -- makes conscious and unconscious choices what information to distribute and how to present this information to us. The mediated message that eventually reaches us has been manipulated. Numerous strategies to carry out such manipulations exist. One of these strategies is framing. 

Framing is the practice of presenting an issue to affect the way people see it [@chong_framing_2007]. It reorganizes existing information already present in people's minds and attempts to direct people's attention towards particular considerations [@druckman_2003_framing]. Numerous experiments have shown that frames can have substantial influence in moving people's opinions [@chong_dynamic_2010;@sniderman_structure_2004]. Despite an abundance of experimental framing research, however, we don't know why some frames are successful in affecting people's opinions and others are not. In other words, we don't know what aspects make frames strong. I provide an avenue of clarification by testing the influence of morals and self-interest in frames.

For some time, scholars have postulated the 'death' of self-interest to explain issue positioning: People eschew their self-interest to defend and vote according to their morals instead, as they consider them more important [@frank_whats_2004; @haidt_2008_morality]. Others, however, cast doubt on these claims: Morals and cultural values do not outweigh self-interest concerns, which in turn represent a significant factor in determining issue positioning [@bartels_2005_homer; @bartels_2006_whats]. Which is it? Have moral concerns displaced self-interest? Does self-interest matter more than postulated by many? I intend to shed some light on these questions with an online framing survey experiment that directly juxtaposes morals and self-interest. Morals are assessed on the basis of Moral Foundations Theory [@haidt_2012_righteous]. To measure self-interest, I widen the widely adopted definition of self-interest to include goals other than material gains, i.e. personal autonomy, health/safety, wealth, and status [@gintis_2017_individuality; @weeden_2017_self-interest]. Demographic information and conviction measurements are used to analyze the influence of each concept. To my knowledge, this setup has not been studied before. In addition to the substantive analysis, both methods developed in chapters II and III are applied and their performance is analyzed.




## Theory {#framing-theory}

### Framing {#framing-theory-framing}

People usually do not have stable, consistent, and informed opinions [@converse_nature_1964; @zaller_nature_1992]. It is therefore possible to influence people's opinion through communication. One of the ways to do so is framing. Framing is the practice of presenting an issue to affect the way people see it [@aaroe_investigating_2011;@druckman_evaluating_2001;@gross_framing_2008]. We learn about healthcare reform through articles, reports, speeches, commercials and social media. This mediated communication possesses tremendous potential influence on our perception of political issues [@iyengar_framing_1996;@kam_risk_2010;@tversky_framing_1981]. Framing research has established that a variety of frames substantively influence how people view and think about issues, such as the ACA [@price_switching_1997;@andsager_how_2000;@callaghan_introduction_2005;@entman_framing_1993;@entman_projections_2004;@gamson_media_1989;@lahav_ideological_2012;@pan_framing_1993;@slothuus_political_2010;@sniderman_structure_2004;@vreese_effects_2004]. When frames influence people's opinion about an issue, we speak of a framing effect. Two different types of framing effects have evolved in the literature: Equivalency and emphasis framing effects.

Equivalency framing effects involve phrasing the same logical content in different ways, i.e. "casting the same information in either a positive or negative light" [@druckman_2004_political, p. 671]. One example is @tversky_framing_1981's death and survival experiment: Presented with a hypothetical disease outbreak in the US that is expected to kill 600 people, respondents were asked to choose between alternating programs. The first group chose between programs A and B. In program A, "200 people will be saved". In program B, "there is 1/3 probability that 600 people will be saved and 2/3 probability that no people will be saved". The second group chose between programs C and D. In program C, "400 people will die". In program D, "there is 1/3 probability that nobody will die, and 2/3 probability that 600 people will die". The factual content given to both groups is of course identical: In both groups, the first program results in the death of 400 people, and the second program has a 66 percent chance of killing all 600 people. The differences is the light cast on this information. The frames given to group 1 focus on lives saved, whereas the frames presented to group 2 center on lives lost. Rationally, both are the same. However, this difference in equalency framing matters: The majority in group 1 chose program A. The majority in group 2 chose program D. Other work focuses on policy evaluations, rather than risk preferences. For example, respondents were found to rate a proposed economic program more favorably when it is framed as resulting in 95 percent employment, instead of it's logical equivalent, 5 percent unemployment [@quattrone_1988_contrasting]. Equivalency framing effects have been likened by some to survey question wording effects [@zaller_nature_1992]. Examples here are the alternate use of "not allow" and "forbid" in reference to Communist speech in the 1970s, which can arguably be described as substantively and logically equivalent [@bartels_2003_democracy, p. 61].

Emphasis framing effects concern putting the stress on a particular aspect, viewpoint, or consideration about an issue in the attempt to get people to look at the issue in the proposed way. Describing the invasion of Iraq as freeing the population and gifting them democracy, as done by the Bush administration, for instance, emphasizes a very different viewpoint than a possible alternative narrative that focuses on the economic benefits of gaining access to oil fields and trade opportunities. Unlike equivalency frames, emphasis frames are not logically identical ways of phrasing the same issue. Instead, they highlight qualitatively different considerations of that issue [@druckman_implications_2001; @druckman_limits_2001; @kinder_1996_divided; @levin_1998_frames; @nelson_1996_issue; @sniderman_structure_2004], forcing people to think about the relative importance of the differing considerations suggested by the frame [@nelson_media_1997].

<!--
More recently, a third (sub-)strain in framing literature has emerged that aims at the separation of framing and persuasion in experimental framing research. It rejects 'classic' definitions of emphasis frames as "reducing a usually complex issue to one or two central aspects" [@nelson_media_1997, p. 568] or identifying "the essence of the issue" [@gamson_1987_changing, p. 143] in favor of "a message that provides an interpretation of an issue or policy by emphasizing which aspect of the issue is relevant for evaluating it, without the frame itself providing any new substantive information about the issue" [@leeper_2020_news, p.4; also see @price_switching_1997]. Whereas persuasion entails the provision of new information to change people's opinions, framing reorganizes existing information already present in people's minds and attempts to direct people's attention towards these particular considerations [@druckman_2003_framing]. Emphasis framing should thus be seen as emphasis of existing information only, in contrast to persuasion that aspires to change people's opinions by "the supply of arguments and evidence" [@kinder_20003_communication, p. 367]. Opinion change in framing thus occurs when people put more or less consideration on previously known aspects about an issue, whereas opinion change in persuasion results from the processing of new information.

We know that emphasis frames work because they move certain information to the top of people's minds [@zaller_nature_1992].
-->

My focus lies on emphasis frames. An abundance of experiments has shown that emphasis frames elicit significant changes in issue positioning [@chong_counterframing_2013;@chong_dynamic_2010;@druckman_2003_framing;@druckman_how_2013;@druckman_limits_2001;@druckman_source_2012;@nelson_media_1997;@slothuus_more_2008]. @brewer_values_2005, for instance, find significant effects for the frames 'School vouchers create an unfair advantage' and 'School vouchers provide help for those who need it'. @druckman_source_2012 provide similar evidence for 'The Affordable Care Act gives more people equal access to health insurance' and 'The ACA increases government costs', while @druckman_how_2013 do so for 'Oil drilling provides economic benefits' and 'Oil drilling endangers marine life'. However, despite the mass of experimental framing research, we still have little insight into what makes an emphasis frame strong. We don't know why some emphasis frames elicit effects and others don't, i.e. we don't know why some frames are strong and other frames are weak. We just know that strong frames are stronger than weak frames. @chong_framing_2007 attempt a differentiation into weak and strong frames. They ask respondents in a pre-test what arguments the respondents consider strong or weak for a variety of chosen issues. Frames containing strong arguments are then deemed strong frames, while frames containing weak arguments are considered weak frames. These weak and strong frames are then used in the subsequent framing experiment. While it is no doubt laudable to explore which arguments in selected political issues are deemed more persuasive than others, this setup does not provide insights as to what actually makes a frame strong or weak. We simply know which arguments (to then be embedded in frames) are considered to be strong and weak, but not why. A major challenge for framing research thus still "concerns the identification of factors that make a frame strong" [@chong_framing_2007, p. 116]. 

In the attempt to address this challenge, scholars have increasingly adopted theory-driven approaches that deduce likely strong frames and subsequently empirically evaluate their theoretical expectations. [@arceneaux_cognitive_2012, p. 280] for instance theorizes that "individuals are more likely to be persuaded by political arguments that evoke cognitive biases" and asserts that messages which highlight out-group threats resonate with respondents to a greater extent. @druckman_framing_2011 report that adding factual information to messages about carbon nanotubes does nothing to enhance their strength and actually makes the message weaker. @feinberg_2013_moral assess whether frames are stronger when they cohere with an individual's personal value system. They frame environmental issues as a matter of moral 'purity', a theme that supposedly correlates with conservative ideology, and find this approach leads to increased conservative support of environmental policies. I attempt to provide a further avenue of clarification by testing the theory that morals contribute to frame strength.





### Morals {#framing-theory-morals}

<!--
What is morality? How are morals/values related to the concept of self? How are they related to political issues? What are the main morals in human interaction?

Conservatives want strong government regulation in personal behaviors and lifestyles (abortion, gay marriage), but autonomy in economics and public goods
Liberals want strong government regulation in economics and public goods (welfare, affirmative action), but autonomy in personal behaviors and lifestyles [@janoff-bulman_2013_surveying]

Political conservatism is based in avoidance motivation
Political liberalism is based in approach motivation

The idea of deciding up-front whether an issue is moral, i.e. examining how people respond in situations that meet pre-set definitions of morality, follows the tradition of moral judgment. In the realm of moral judgment, researchers decide, objectively along a set of criteria, whether an issue is moral. This stands in contrast to moral conviction. In moral conviction theory, morality lies in the eye of the beholder, i.e. people decide whether they consider an issue to be moral. Moral conviction "classifies stimuli as moral or non-moral as a function of individuals' perceptions of situations rather than according to characteristics of the situation" [@bauman_2009_mind, p. 342]. Rather than presupposing the morality of an issue externally, it is argued that people recognize a moral sentiment when they experience one, as it touches their perceived connection of what is right and wrong [@bandura_1986_social; @cervone_2004_architecture; @goodwin_2008_psychology; @skitka_2008_morality]. This recognition and perception, however, varies considerably depending on the person experiencing the potentially moral situation. Defining an issue or situation as moral then becomes a subjective endeavor for each individual person and their psychological reality [@haidt_2001_emotional; @haidt_2003_emotional; @morgan_2010_moral; @skitka_2008_moral]. What I consider to be moral might not be moral to you, and vice versa. The literature shows that moral conviction represents an important force that guides citizen behavior and development of public opinion [@converse_nature_1964;@skitka_moral_2005;@skitka_moral_2011;@smith_typologies_2002;@tatalovich_moral_2011;@zaller_nature_1992]. This has consequences for survey design. Rather than deciding pre-survey which issues are moral (moral judgment), researchers "directly assess the extent that a given issue engages moral conviction and then use those responses to classify whether situations are or are not moral for a specific individual" [@bauman_2009_mind, p. 343]. 

[@bandura_1986_social; ; @goodwin_2008_psychology]
[@morgan_2010_moral; @skitka_2008_moral]

Morals in the Western world focus mostly on the ethic of autonomy (i.e. harming, cheating, or oppressing other people) [@haidt_2012_righteous].

Conservatives resist change, emphasize social order, see liberty as the right to be left alone (e.g. with regards to the environment or workers' rights), and define fairness in terms of proportionality (i.e. those who work hardest should be paid the most). 

Liberals embrace change, emphasize social justice, see liberty as the right of vulnerable populations (minorities, children, animals) to be defended by the government, and define fairness as equal provision for all. 
-->


Two of the main ingredients of public opinion are commitment to principles (i.e. morals) and interests that citizens see at stake [@kinder_1998_opinion]. Morals play a role in establishing one's self-concept and identity. Moral arguments can achieve a much higher emotional connection with people because they invoke people's values and feelings [@bauman_2009_mind;@skitka_moral_2005;@skitka_moral_2011;@haidt_moral_2003;@tatalovich_moral_2011]. Emotions play an important role in how people conceptualize moral stimuli since people feel emotionally committed to their values [@ryan_reconsidering_2014; @suhay_2008_group; @tetlock_1996_revising]. Appeals to values/morals tend to be more successful than non-moral appeals "especially when the moral principles invoked resonate with the individuals targeted by the appeal" [@feinberg_2013_moral, p. 57]. Moralization literature conceptually defines moral arguments as (1) near-universal standards of truth, (2) almost objective facts about the world, and (3) independent of institutional authority [@skitka_psychology_2010]. The strength of attitudes meaningfully differs when they are held with moral conviction [@baron_protected_1997;@bennis_costs_2010;@ditto_motivated_2009;@tetlock_correspondence_2003]. It is widely argued that people rely to a disproportionate extent on moral arguments to form their opinions [@ryan_no_2014;@ryan_reconsidering_2014;@smith_typologies_2002].  

Moral arguments are ubiquitous in political issues because they are essential to how people perceive and make sense of the world around them [@cervone_2004_architecture;@frank_whats_2004;@mooney_public_2001;@skitka_2008_morality;@tatalovich_moral_1994]. A lot of scholarly work tries to establish a distinction between moral and non-moral issues, yet agreement on the definition of a 'moral issue' remains elusive. To some, an issue is moral when at least one side sees the issue as threatening a core value/principle and/or uses moral arguments to support their position [@mooney_public_2001; @haider-markel_1996_politics]. To others, moral issues are based on values rooted deeply within people's belief systems [@biggers_2011_when; @glick_2001_physician-assisted]. Yet another strain sees morality as intrinsic to some issues, i.e. nontechnical issues that are easy to understand or issues that concern fundamental aspects of life and death [@studlar_2001_what; @tavits_2007_principle]. Yet others again assert that economic issues are not to be considered moral [@abramowitz_1995_abortion; @engeli_2012_theoretical; @mooney_1995_legislative; @tatalovich_moral_2011] despite evidence to the contrary: @ryan_reconsidering_2014 finds evidence that some people perceive distinctly economic issues such as labor relations laws or social security reform in moral ways. In addition, studies on abortion also show that, despite the media's contrary depiction, not everyone conceives of it as a moral issue [@mullen_2006_exploring; @skitka_2002_means; @skitka_moral_2005]. Assertions of moral and non-moral issues are, in my eyes, misleading and unnecessary. Instead, we should concern ourselves with the moral and non-moral content of each respective issue. I thus eschew moral and non-moral issue definitions and focus on moral and self-interest frames within issues, rather than the moral nature of the issues themselves.

In normative terms, we differentiate between prescriptive and proscriptive morality, which are based on approach-avoidance differences in self-regulation [@carnes_2012_harm]. Prescriptive morality is sensitive to positive outcomes and focused on what we should do. Proscriptive morality is sensitive to negative outcomes and focused on what we should not do [@janoff-bulman_2009_proscriptive]. Based on this categorization, Haidt and his colleagues developed Moral Foundations Theory (MFT), which encompasses cognitive foundations of moral matrices and has become widely adopted in moralization literature [@graham_2009_liberals; @haidt_2001_emotional; @haidt_2003_emotional; @haidt_2012_righteous; @haidt_moral_2003; @haidt_2004_intuitive; @haidt_2007_moral; @haidt_2007_synthesis; @haidt_2007_when; @haidt_2008_morality; @haidt_2010_morality; @hofmann_2014_morality; @schein_2017_theory; @clifford_2015_moral; @koleva_2012_tracing; @feinberg_2013_moral; @clifford_2013_words]. These foundations are shown in Table \ref{framing-foundations}.

\begin{table}[ht]
\caption{Foundations of Moral Intuitions}
\centering
\resizebox{\textwidth}{!}{
\begin{tabular}{>{\itshape}l ll >{\itshape}l l}
\bottomrule 
\midrule
\multicolumn{2}{c}{\textbf{Positive}} & & \multicolumn{2}{c}{\textbf{Negative}}\\
\cmidrule{1-2}
\cmidrule{4-5}
Care & Cherishing, protecting others & & Harm & Hurting others\\
Fairness & Rendering justice by shared rules & & Cheating & Flouting justice/shared rules\\
Loyalty & Standing with your group & & Betrayal & Opposing your group\\
Authority & Submitting to tradition/authority & & Subversion & Resisting tradition/authority\\
Sanctity & Repulsion at disgust & & Degradation & Enjoyment of disgust \\
Liberty & Acting without constraint & & Oppression & Dominate/Constrain others\\
\bottomrule
\multicolumn{5}{l}{\footnotesize{Positive and negative foundations are conceptual opposites.}} \\
\end{tabular}}
\label{framing-foundations}
\end{table} 


Moral intuitions are a powerful psychological mechanism that underlies issue positions [@koleva_2012_tracing]. Care/Harm developed as the response to the adaptive challenge of protecting and caring for children. It makes us sensitive to signs of suffering and activates us to care for those who are being harmed. Fairness/Cheating developed as the response to acts of cooperation or selfishness that people show towards us. It makes us trust fair actors and punish cheaters. Loyalty/Betrayal developed to meet the adaptive challenge of forming and maintaining cohesive coalitions. It makes us reward loyalty and ostracize those who betray us. Authority/Subversion developed as the response to forging beneficial relationships within social hierarchies. It makes us sensitive to signs that people do not behave in accordance with their social position. Sanctity/Degradation developed as a response to the challenge of living in world full of pathogens and parasites. It binds us into moral communities by shared notions of sacredness. Liberty/Oppression developed as a response to the challenge of living in small groups whose members can dominate and constrain us. It makes us value freedom and reject repression.

Because of the deep connection between morals and emotions, people have a tendency to internalize and defend their values. This "makes it very difficult for people to consider the possibility that there might really be more than one form of moral truth, or more than one valid framework for judging people or running a society" [@haidt_2012_righteous, p. 111]. Haidt distinguishes the use of these foundations by ideology. Liberals are said to utilize a three-foundation morality, whereas conservatives allegedly use all six foundations. Additionally, both sides focus on different aspects in the three foundations they share (Care/Harm, Fairness/Cheating, Liberty/Oppression). Conservatives emphasize society's protection and security and aim to prevent losses and generally negative outcomes, while liberals emphasize the provision of welfare for others and aim to advance gains and generally positive outcomes. Both seek normatively 'good' outcomes for society, but with different orientations [@janoff-bulman_2009_provide; @janoff-bulman_2009_proscriptive; @janoff-bulman_2013_surveying].

While the liberal/conservative divide of course plays a role in opinion formation, it is not central to moral analyses. Liberals and conservatives differ on average with respect to the foundations, but the foundations themselves are what matter most. My focus lies on the juxtaposition of morality and self-interest.




### Self-Interest {#framing-theory-self_interest}

<!--
[@kahneman_fairness_1986; @weatherford_economic_1983]

Unenlightened self-interest [@bartels_2005_homer]: 
A majority of Americans supported the 2001 and 2003 Bush administration tax cuts, even though they were designed to disproportionately benefit the rich. Economic self-interest can't explain this, since the majority of Americans suffered economically from the cuts. As Bartels shows, neither can people's attitudes towards the tax burden born by the rich. 

It follows the idea that the individual and society both benefit most when each individual pursues his or her own interest. This assumption has been highly influential in many theories of human behavior, has pervaded models of neoclassical economics, political science, sociology, as well as philosophy, and is not restricted to particular issues. It presents self-interest as the potential cardinal human motive: "I assume that most people most of the time act in their own self-interest" [@fiorina_congress:_1977, p. 38].

@sears_role_1991 indeed suggest objective (amount of income, state of personal finances) and subjective (perception of the amount of taxes paid) parameters as the most suitable statistical measurements to accurately capture any evidence for self-interest-motivated human behavior.

On the other hand, others find that the unemployed actually do not favor policies to increase employment more than those with jobs [@schlozman_1979_injury], people with health concerns do not show stronger support for government health insurance than others [@sears_self-interest_1980], working women do not differ from homemakers in their attitudes towards benefits for women in the workplace [@sears_1990_origins], and pocketbook voting does not determine congressional votes [@kiewet_macroeconomics_1983].

The unemployed line up behind policies that help the unemployed, uninsured Americans favor a government role in health insurance, and African-Americans are the biggest supporters of race-based affirmative action [@weeden_2014_hidden]. 

"Thus, we think that it’s generally appropriate in studying self-interested political views to piece together a more objective view of respondents’ personal interests (through demographic and related measures) rather than asking them to directly characterize their motives or their views on who benefits from particular policies" [@weeden_2017_self-interest, p. 87].
-->


Two of the main ingredients of public opinion are commitment to principles (i.e. morals) and interests that citizens see at stake [@kinder_1998_opinion]. Section \ref{framing-theory-morals} covers morals. This section addresses self-interest. 

Self-interest refers to actions or behaviors that elicit personal benefit. When acting in self-interest, individuals look out for themselves in life and act on the grounds of personal gains [@arrow_1967_values; @downs_economic_1957; @ferejohn_paradox_1974; @fiorina_congress:_1977; @olson_logic_1965; @coleman_1986_individual; @riker_theory_1968; @sears_role_1991]. In neoclassical economics, this claim is extended to the overall postulation of human beings as \textit{homines economici} [@coleman_1986_individual]; creatures who act strictly rationally with the intent to maximize utility at all times. In political psychology, scholars instead focus on the importance of self-interest as a motivation for opinions on political issues.

In the 1960s, self-interest was considered a major determinant of opinions on political issues. @campbell_american_1960 for instance report that people with less income and education are more likely to support a strong government role in the provision of social welfare, stating that "people presented with certain policy alternatives can do a reasonable job of selecting responses that appear to further their self-interest" (p. 208). Empirical research from the 1970s and 1980s appears to confirm this [@batson_altruism_1991; @etzioni_moral_1988; @feldman_economic_1982; @feldman_economic_1984; @friedland_beyond_1989; @hirschman_against_1985; @kohn_brighter_1990; @lau_cognitive_1981; @lerner_belief_1980; @mansbridge_preface_1990; @miller_power_1996; @schwartz_battle_1986; @sears_tax_1985; @weatherford_economic_1983]. @hawthorne_individual_1987 find that income level and tax bracket significantly predicts support for the tax cuts in the 1978 federal Tax Revenue Act. @lau_proposition_1983 identify a similar relationship for high taxpayers in their Massachusetts income tax study. @coughlin_economic_1990 discover that higher income citizens oppose redistribution slightly more than lower income ones. @sears_self-interest_1980 and @sears_inducing_1983 find evidence for pocketbook voting in their studies on government-guaranteed full employment. @courant_why_1980 discover modest but consistent effects for the perceived property tax burden in Michigan. @lau_fact_1990 find a significant relationship between perceived financial situation and anti-incumbent voting. The analysis by @sears_inducing_1983 reveals that perceived personal federal tax burden predicts support for the tax cuts specified in the 1979 Kemp-Roth bill. @bartels_2005_homer identifies a high subjective tax burden as the source of support for the 2001 and 2003 Bush tax cuts. @sears_tax_1985 similarly find that citizens with a high subjective tax burden act out of self-interest in the so-called California Tax Revolt at the end of the 1970s.

Despite this evidence, an abundance of criticism has claimed the inadequacy of self-interest as a major predictor of human behavior. @miller_power_1996 call "homo economicus (...) a social construction, not a biological entity" (p. 45). Human behavior is argued to be too complex and much more than self-interest is claimed to come into play when people think about what they want in life [@batson_altruism_1991; @friedland_beyond_1989; @kohn_brighter_1990; @lerner_belief_1980; @mansbridge_preface_1990; @mansbridge_1990_relation; @schwartz_battle_1986; @sen_rational_1977; @tyler_1990_people]. The study of social movements, for instance, provides clear evidence that motivations other than self-interest also majorly account for human behavior [@mansbridge_rise_1990]. The overall most important reasons for humans' choices are affective and normative [@etzioni_moral_1988] and we need to shift our focus away from obsession with self-interest and towards moral values [@hirschman_against_1985]. The dominant theories of motivation are fundamentally based on personal gains and miss the influence that values and ideologies have on people's attitudes towards policies [@sears_self-interest_1990]. People are more interested in the fairness of procedures and policies than the self-beneficial outcomes of these processes [@tyler_justice_1990]. It is possible and plausible that self-interest plays a role in opinion formation, but even then it does not play the only role [@chong_when_2001; @citrin_1990_self-interest; @miller_norm_1999; @sears_self-interest_1990]. It is argued that self-interest is limited in explanatory scope [@chong_when_2001; @huddy_2013_from; @lewis-beck_2008_american; @kinder_1998_opinion; @lau_2030_self-interest; @sears_self-interest_1990] and only applies to short-term material gains [@sears_self-interest_1980]. As a result, self-interest is argued to be negligible: "Many political scientists used to assume that people vote selfishly, choosing the candidate or policy that will benefit them the most. But decades of research on public opinion have led to the conclusion that self-interest is a weak predictor of policy preferences" [@haidt_2012_righteous, p. 85]. Furthermore, standard demographic measures such as education, income, race, and gender are not deemed adequate indicators of self-interest, thus discounting findings from the 1960s [@kinder_1998_opinion; @sears_self-interest_1990]. 

These assertions strike me as odd. For one, empirical evidence appears to indicate that self-interest at least plays some role in economic aspects. For another, arguing that self-interest does not matter because of its exclusive focus on material gains after having defined self-interest in precisely this way has the feel of a snake biting its own tail. Of course self-interest does not account for many policy preferences when only material gains count as self-interest. After all, material gains are not all that humans desire. But should the definition of self-interest be so narrow? It seems perfectly reasonable that people have all kinds of self-serving preferences, from having more money to gaining prestige, having sex, or wishing success for one's children, among many others [@becker_1996_accounting; @owens_2014_material; @weeden_2015_losing; @weeden_2016_people]. Instead of a restricted categorization as purely economic gains, self-interest can be defined as "advancing any of a range of people's typical goals, whether directly involving material gain or not, whether involving immediate gain or something more subtle that advances someone's progress over the longer term" [@weeden_2014_hidden, p. 38]. By restricting self-interest to financial benefits and declaring ordinary demographic effects uninterpretable, scholars defined away any chance of self-interest being a major determinant of opinions on political issues. I see no reason for such restrictions. 

Following evolutionary psychology, humans have self-interests that reach beyond material gains and include cultural as well as social aspects [@buss_2015_handbook; @petersen_2016_evolutionary]. Self-interest thus applies not only to economic aspects but also to various social and cultural domains as well [@kurzban_2010_sex; @nteta_2013_united]. Self-interest is here defined as related to personal autonomy, health/safety, wealth, and status [@gintis_2017_individuality]. Demographics are argued to provide clues to particular outcomes that help or harm people's self-interests, which enables us to predict which opinion they have. By linking demographic measures with answers from the General Social Survey, @weeden_2014_hidden find strong links between self-interest and meritocracy, discrimination, sexual lifestyles, religiosity, abortion, and marijuana legalization. Crucially, not all demographics provide clues about all kinds of issues. Religion can provide insights into people's views on abortion, but is unlikely to do so for immigration. Household income can predict views on taxes but probably not on legalizing marijuana [@weeden_2017_self-interest].

From this perspective, self-interest arguably matters most for issues that greatly affect people's everyday interests [@descioli_2020_selfish; @kurzban_2010_everyone; @sznycer_2017_support]. Rather than focusing on material gains -- such as people's perceived tax burden [@bobo_whites_1983] -- @weeden_2014_hidden identify issues related to sex/reproduction (pre-marital sex, pornography, abortion, birth control access) and government spending on health care as prime candidates for a major influence of self-interest. Sexually conservative, married people with high regular church attendance can be predicted to be pro-life and against pre-marital sex because it aligns with their chosen lifestyle. Wealthy, white, heterosexual, Christian men can be predicted to oppose government redistribution of wealth as such a policy would endanger their own position. In both cases, it is in these individuals' self-interest to take these issue positionings because these issues directly relate to their lives. Such a connection is said to be less pronounced for issues such as the environment or the military, as they are deemed too remote for too many people to affect everyday lives.





## Design {#framing-design}

Each of the previous areas has been studied, but they have not been applied together. An abundance of framing research exists and we know that emphasis frames can be successful in directing people's attention towards particular considerations of an issue, but we still don't know why some emphasis frames succeed while others fail. We know that morals play a large role in people's issue positioning and that self-interest accounts for some human behavior, but we don't know how much self-interest and morals matter in direct comparison when people choose issue positions. I conduct a framing experiment that explores what we don't know. I investigate how morals and self-interest contribute to persuasive strength in emphasis frames.

Juxtaposing morals and self-interest in frames follows the recognition that people don't just want to satisfy their interests, but neither do they set aside their self-regarding preferences in favor of some non-self-regarding ones [@stoker_1992_interest]. Both concepts are in constant movement, depending on the situation. People deal with the 'central problem of ethics': "how the lives, interests, and welfare of others make claims on us, and how these claims, of various forms, are to be reconciled with the aim of living our own lives" [@nagel_1970_possibility, p. 142]. Support for issues, for instance the welfare state, is based on "generalized and reciprocal self-interest" [@baldwin_1990_politics, p. 299], i.e. it depends on both value-based attitudes and immediate self-interest. Opinions can be influenced by self-interest or alterations in empathy towards others [@hacker_insecure_2013; @rehm_2012_insecure]. It is often difficult to tell which is which: @frank_whats_2004 claims Republicans have duped rural and working-class Americans into voting against their self-interest by supporting Republican tax cuts that negatively affect them financially. @bartels_2005_homer argues that they instead vote in unenlightened self-interest because they perceive their personal tax burden to be too high and (falsely) believe tax cuts can lower them. @haidt_2012_righteous, finally, states that they vote for their moral interest, as they don't want the country to devote itself primarily to the pursuit of social justice. It is difficult to assess which is correct.

Previous studies and experiments on moral framing that utilize MFT focus on partisan division [@clifford_2013_words; @feinberg_2013_moral; @koleva_2012_tracing; @slothuus_political_2010; @wolsko_2016_white]. While party ID of course matters in any political analysis, partisanship is not central to analyses of moral concerns. Instead, I utilize MFT to focus on the moral vs. self-interest juxtaposition within framing. I combine emphasis framing with aspects of MFT and the literature on self-interest.

<!--
Framing on morals/values so far:
@slothuus_political_2010: how framing political messages in terms of values consistent with partisan motivations shapes acceptance of these messages
@wolsko_2016_white: conservatives who receive a message framed on the moral foundations that their in-group strongly endorses (loyalty, authority, sanctity) are likely to believe more in climate change 
@feinberg_2013_moral: reframing environmental messages in line with partisan moral values decreases polarization gap between liberals and conservatives

Applying Moral Foundation Theory, both frames in @brewer_values_2005 could be categorized as containing moral arguments, even though the authors do not explicitly do so. 'School vouchers create an unfair advantage' can be argued to contain the negative moral foundation of \textit{Cheating}, while 'School vouchers provide help for those who need it' contains the positive moral foundations of \textit{Care} and \textit{Fairness}. 'The ACA gives more people equal access to health insurance' [@druckman_source_2012] also could be said to contain the positive moral foundations of \textit{Care} and \textit{Fairness}, while 'Oil drilling endangers marine life' [@druckman_how_2013] contains the negative moral foundation of \textit{Harm}. 
In the case of @druckman_source_2012, 'The Affordable Care Act gives more people equal access to health insurance' contains a positive, i.e. support-inducing, moral argument, while 'The ACA increases government costs' contains a negative, i.e. opposition-inducing, non-moral argument. They act in opposite directions. A comparison of these frames alone does not yield sufficient results as we would not be able to identify the exact cause of the framing effect. Is 'The Affordable Care Act gives more people equal access to health insurance' strong because it supports the issue or because it contains a moral argument? Similarly, is 'The ACA increases government costs' strong because it opposes the issue or because it contains a non-moral argument? This set-up cannot answer these questions. 

\noindent "Self-interest is commonly defined as a short to medium-term impact on the material well-being of an individual's own personal life (or that of his or her immediate family)" [based on @sears_role_1991, p. 16].

\noindent "Morals concern what people should or should not do" -- 'Moral' description from Ryan or Skitka?. An action of yours is moral if it treats others the way you would like others to treat you (Dal Bo and Dal Bo 2014)

Following moral conviction theory, each respective respondent decides for themselves whether they consider each issue moral by answering moral conviction measures such as "To what extent is your opinion on [issue] a reflection of your core moral beliefs and convictions?" [based on @ryan_no_2014; @skitka_moral_2005; @skitka_psychology_2010]. Note that respondents 'rate' each issue in terms of morality but without actually stating their position on the issue. This is to avoid anchoring.

I design frames to correspond with the partisan messages identified by Haidt and assign them according to respondents' self-identification on party ID. This means a self-identified Democrat receives a fairness/cheating frame built on aspects of fairness/cheating that most apply to liberals. Conversely, a self-identified Republican receives a fairness/cheating frame designed to reflect fairness/cheating aspects most dear to conservatives. Independent respondents randomly receive the liberal or the conservative version.

Taxes, abortion, climate change, school choice, takings, same-sex marriage, collective bargaining rights, capital punishment, school vouchers, Black Lives Matter, social welfare/redistribution, gun control, animal testing, health care, urban growth/conservation, federal assistance to the poor, immigration, Patriot Act, gambling, Corona, social spending/reducing the deficit, minimum wage

Everyone pays taxes and can state how they feel about their tax burden. Respondents' self-identified income indicates which tax bracket they fall into and gives insights into their self-interest when presented with a fictitious tax policy (see the frames below). We can also assess perceived self-interest by asking "Do you feel you are asked to pay more than you should in federal income taxes, about the right amount, or less than you should?" (question wording from the ANES).

Like corporations and administrations, people need to maintain positive public images that are typically most effective when stories are spun to disguise these principal objectives [@weeden_2014_hidden]. People often take credit for having brought about good outcomes, and blame others, chance, fate, or the gods for bad outcomes [@kurzban_2010_everyone]. The result, when it comes to political opinions, is a messy combination of preferences for policies that advance people's own inclusive in- terests coupled with a stubborn set of talking points used to insist that, in fact, these policy preferences really just come from a well-reasoned concern for the welfare of everyone. I have the positions I have because I am a smart person and my favored policies are smart policies. I have the positions I have because I am a good person and my favored policies are good for society.
-->

Issues are selected from previous research and based on suitability to assess self-interest. In order to assess self-interest, all issues need to apply directly to respondents' daily lives. Following @weeden_2014_hidden, I choose government spending on healthcare and abortion. Everyone is affected by healthcare in their lives, so everyone has a vested self-interest in this issue. At the same time, how much the government should be involved in the provision of healthcare coverage is the subject of great debate. Similarly, the vast majority of people are affected by the issue of abortion, resulting in viable cause for self-interest, while the topic is also of great controversy in moral terms.

Each respondent is presented with one of five randomly assigned frames: An issue-supporting moral frame, an issue-opposing moral frame, an issue-supporting self-interest frame, an issue-opposing self-interest frame, or the control frame. The design consists of issue-supporting and issue-opposing frames in order to control for both signs in determining frame strength. The self-interest frames aim to activate each respondent's self-interest as identified by @weeden_2014_hidden. The moral frames are designed on the basis of Moral Foundations Theory. For simplicity and to avoid cluttering, I only use the foundation that most applies to each issue and to the majority of people. For both issues, that is Care/Harm. Support/Opposition for/to the frame's content is assessed on a 5-point Likert scale.

To measure self-interest, respondents answer a series of demographic questions related to each issue (questions Q12 to Q22 in the questionnaire). As described above, these demographics provide a match for each issue to determine underlying self-interest. For government spending on healthcare, for instance, those with less wealth and income, those with little education, minorities, women, and those with young children are likely to have a strong self-interest in the issue. Abortion is said to have major relationships with personal lifestyles as well as with religion and church attendance. All question wordings are based the ANES, CCES, and GSS surveys. I also measure the strength of Care/Harm for each respondent with questions taken from the Moral Foundations Questionnaire.






### Expectations {#framing-design-expectations}

<!--
-- We can test which issues are considered more moral than others
-->

Persuasion literature asserts that people with strongly held attitudes are not easily persuaded with arguments to the contrary. This indicates that it is difficult to move the attitudes of respondents who show high scores on moralization or self-interest, no matter what frame they are presented with. This in turn suggests that we can only move the attitudes of people who don't hold their attitudes strongly, i.e. those who score in the lower range on moralization and self-interest. For the respondents with strongly held attitudes on the issue, their support/opposition for/to the issue should be statistically the same across all frames, since their attitudes are set and can't easily be moved. For the respondents without strongly held attitudes on the issue, the frames should move responses towards support or opposition, depending on the direction of the frame. For these people, we can explore whether the moral or the self-interest frames cause bigger shifts. Moral arguments are said to relate more strongly than non-moral ones since they are deeply connected to emotions. Non-moral arguments, on the other hand, are said to be more loosely connection to emotions and thus deemed less powerful [@haugtvedt_1994_message; @johnson_1989_effects]. This would suggest that moral frames exert a stronger influence on respondents' issue positioning than self-interest frames. I thus pose the following hypotheses:

\vspace{0.3cm}
\begin{adjustwidth*}{+1cm}{+1cm}
\noindent \textbf{H1.} Respondents with strongly held moral or self-interested attitudes are not moved by any frames.\\
\textbf{H2.} Respondents without strongly held attitudes are moved by self-interest and moral frames.\\
\textbf{H3.} Respondents without strongly held attitudes are moved further by moral frames than self-interest frames.
\end{adjustwidth*}




## Data {#framing-data}

The designed frames are pre-tested for their moral and self-interest content on MTurk. The confirmed frames are subsequently applied in a survey experiment fielded online with Lucid.


### Pre-Tests {#framing-data-pre_test}

Survey questions are best designed if researchers have a firm grasp of the underlying realities that participants have to report [@carpini_1993_measuring;@stanley_2016_using;@conover_1991_nature]. Following this line of argument, pre-testing frames with participants who are not part of the main survey experiment is crucial in frame analysis. These participants are exposed to the designed frames and asked whether they reflect the core ideas behind morals and self-interest. This pre-test structure builds on work by @slothuus_political_2010 and @chong_framing_2007, following the mass communication and persuasion literature [@okeefe_2002_persuasion]. The pre-test is carried out on Amazon's online platform MTurk. MTurk is a service where researchers can host tasks to be completed by anonymous participants. Participants receive financial compensation for their work and Amazon collects a commission. MTurk samples have been shown to be internally valid in survey experiments [@berinsky_evaluating_2012]. The use of MTurk in political science experiments has increased dramatically over the past decade and is now common practice [@hauser_attentive_2016]. This pre-test represents a thorough, robust safety net to ensure that the designed frames represent arguments relating to self-interest/morals and connect with participants, which in turn ensures meaningful survey results.



### Survey Experiment {#framing-data-survey}

The survey experiment builds on the insights from the pre-test. It is fielded online for a random sample of U.S. adults with Lucid. Lucid has been shown to be equally reliable and performs well on a national scale in survey experiments [@coppock_2019_validating]. The survey collects demographic information on standard political science variables and applies all successfully pre-tested frames on all chosen issues. Both methods from the previous chapters are applied. Respondents are blocked on ordinal variables with the method from chapter I. The results are evaluated substantively to reveal the effect of morals and self-interest in respondents' issue positions. The ordinal variable imputation method from chapter II is also applied to artificially inserted missing data. This allows us to assess the performance of ordinal variable imputation method by comparing the imputation results with the true values of the completely observed data.






## Results {#framing-results}

### Pre-Tests {#framing-results-pre-tests}

### Survey Experiment {#framing-results-experiment}

#### Imputation {#framing-results-experiment-imputation}

## Conclusion {#framing-conclusion}


